


export const typeArray = ["Noise Report", 
"Streetlights", 
"Encampments", 
"Sidewalk or Curb", 
"General Request - MTA", 
"General Request - PUBLIC WORKS", 
"MUNI Feedback", "Street Defects", 
"Blocked Street or SideWalk", 
"Graffiti", 
"Street and Sidewalk Cleaning", 
"Damaged Property", 
"Sewer Issues", 
"Illegal Postings"] 

export const districtArray = ["Cayuga", 
                        "Mint Hill", 
                        "Tenderloin", 
                        "Castro", 
                        "Marina", 
                        "Mission Dolores", 
                        "South of Market", 
                        "Produce Market", 
                        "Merced Heights", 
                        "Excelsior",
                         "Mission", 
                         "Outer Richmond", 
                         "Lower Nob Hill", 
                         "Nob Hill", 
                         "Inner Richmond", 
                         "Portola", 
                         "Anza Vista", 
                         "Noe Valley", 
                         "Potrero Hill", 
                         "Cathedral Hill", 
                         "Duboce Triangle", 
                         "Ingleside", 
                         "Presidio Heights", 
                         "Dolores Heights", 
                         "Central Waterfront", 
                         "Outer Sunset", 
                         "Oceanview", 
                         "Visitacion Valley", 
                         "Western Addition", 
                         "Financial District", 
                         "Bayview", "Presidio Terrace", 
                         "Civic Center", 
                         "Fairmount", 
                         "Peralta Heights", 
                         "Silver Terrace", 
                         "Hunters Point", 
                         "Lone Mountain", 
                         "Downtown / Union Square", 
                         "Showplace Square", 
                         "Holly Park", 
                         "Inner Sunset", 
                         "Bernal Heights", 
                         "Telegraph Hill", 
                         "Glen Park", 
                         "Hayes Valley", 
                         "Miraloma Park", 
                         "Alamo Square", 
                         "Diamond Heights", 
                         "Russian Hill", 
                         "Lakeshore", 
                         "Haight Ashbury", 
                         "Sutro Heights", 
                         "Upper Market", 
                         "Golden Gate Park", 
                         "Parkmerced", 
                         "Clarendon Heights", 
                         "South Beach", 
                         "Parnassus Heights"]



 