


export const typeArray = ["Noise Report", 
"Streetlights", 
"Encampments", 
"Sidewalk or Curb", 
"General Request - MTA", 
"General Request - PUBLIC WORKS", 
"MUNI Feedback", "Street Defects", 
"Blocked Street or SideWalk", 
"Graffiti", 
"Street and Sidewalk Cleaning", 
"Damaged Property", 
"Sewer Issues", 
"Illegal Postings"] 

export const districtArray = [ "Mission Dolores", 
                        "Financial District", 
                        "Lower Pacific Heights", 
                        "Miraloma Park", 
                        "Pacific Heights", 
                        "South of Market", 
                        "Castro", 
                        "Mission", 
                        "Nob Hill", 
                        "Outer Sunset", 
                        "Tenderloin", 
                        "Produce Market", 
                        "Russian Hill", 
                        "Laurel Heights / Jordan Park", 
                        "Marina", 
                        "Bayview", 
                        "Civic Center", 
                        "Clarendon Heights", 
                        "Eureka Valley", 
                        "Excelsior", 
                        "Ingleside", 
                        "St. Francis Wood", 
                        "Inner Richmond", 
                        "Cathedral Hill", 
                        "Dolores Heights", 
                        "Bernal Heights", 
                        "Polk Gulch", 
                        "Duboce Triangle", 
                        "Bret Harte", 
                        "Visitacion Valley", 
                        "West Portal", 
                        "Lower Nob Hill", 
                        "Downtown / Union Square", 
                        "Stonestown", 
                        "Outer Richmond", 
                        "Japantown", 
                        "Potrero Hill", 
                        "Mission Terrace", 
                        "Mission Bay", 
                        "Haight Ashbury", 
                        "Lower Haight", 
                        "Presidio National Park", 
                        "Merced Heights", "Portola", 
                        "Western Addition", 
                        "Crocker Amazon", 
                        "Sherwood Forest", 
                        "Showplace Square", 
                        "Rincon Hill", 
                        "Cole Valley"] 



 